### ISSUE TITLE
the repository name beginning with "-" may cause ambiguity

### ISSUE THREAD

**Issue by SeanChao** [tx19980520/-the-generality-of-mao-ze-dong-thoughts-#2]
The repository name begins with "-", which may cause unexpected/incovenient interpretation as a parameter in command lines. Like:
`bash: cd: -t: invalid option`
would you plz fix that :-D

**Comment by tx19980520** [comment]
> The repository name begins with "-", which may cause unexpected/incovenient interpretation as a parameter in command lines. Like:
> `bash: cd: -t: invalid option`
> would you plz fix that :-D

I have changed all the - to _

**Comment by SeanChao** [comment]
thx😆
